name: test

on: workflow_dispatch

env:
  TESTS_PATH: "${{ github.workspace }}/tests" 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Building
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Testing
        run: |
          docker exec -i fochan-db-1 psql -U postgres database < example.sql
          rustup install nightly
          cargo +nightly test
        # Test via bash script
        # run: |
        #   for script in tests/*.sh
        #   do
        #     echo "Script name: $script"
        #     echo "Executing/Output:"
        #     echo ""
        #     bash $script || break
        #     echo ""
        #     echo ""
        #   done

