name: test

on: 
  push:
    branches: [ "main" ]

env:
  TESTS_PATH: "${{ github.workspace }}/tests" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Testing
        run: |
          docker run --name db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=database -p 5432:5432 -d postgres:latest
          rustup install nightly
          cargo install diesel_cli --no-features --features postgres
          diesel setup --database-url='postgres://postgres:postgres@localhost/database'
          cargo +nightly test
        # Test via bash script
        # run: |
        #   for script in tests/*.sh
        #   do
        #     echo "Script name: $script"
        #     echo "Executing/Output:"
        #     echo ""
        #     bash $script || break
        #     echo ""
        #     echo ""
        #   done

