name: test

on: 
  push:
    branches: [ "main" ]

env:
  TESTS_PATH: "${{ github.workspace }}/tests" 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Building
      #   uses: hoverkraft-tech/compose-action@v1.5.1
      #   with:
      #     compose-file: "./docker-compose.yml"

      - name: Testing
        run: |
          docker image pull postgres:latest
          docker run --name db -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:latest
          rustup install nightly
          cargo install diesel_cli --no-default-features --features postgres
          diesel setup --database-url='postgres://postgres:admin@localhost/database'
          diesel migration run --all 
          cargo +nightly test
        # Test via bash script
        # run: |
        #   for script in tests/*.sh
        #   do
        #     echo "Script name: $script"
        #     echo "Executing/Output:"
        #     echo ""
        #     bash $script || break
        #     echo ""
        #     echo ""
        #   done

