name: build and deploy

on:
  push:
    branches: [ "main" ]

env:
  TEST_PATH: "${{ github.workspace }}/tests/test_file" 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Testing
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - run: echo ${{ env.TEST_PATH }}
